services:
  - type: web
    name: codeplayground-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: DATABASE_URL
        sync: false
